/*
 * generated by Xtext
 */
package org.inria.diverse.logo.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.inria.diverse.logo.dsl.ui.internal.LogoDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LogoDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LogoDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LogoDSLActivator.getInstance().getInjector(LogoDSLActivator.ORG_INRIA_DIVERSE_LOGO_DSL_LOGODSL);
	}
	
}
