/*
 * generated by Xtext
 */
package org.inria.diverse.logo.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.inria.diverse.logo.dsl.services.LogoDSLGrammarAccess;

public class LogoDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private LogoDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.inria.diverse.logo.dsl.parser.antlr.internal.InternalLogoDSLParser createParser(XtextTokenStream stream) {
		return new org.inria.diverse.logo.dsl.parser.antlr.internal.InternalLogoDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "LogoProgram";
	}
	
	public LogoDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LogoDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
