/*
 * generated by Xtext
 */
package org.inria.diverse.logo.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LogoDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/inria/diverse/logo/dsl/parser/antlr/internal/InternalLogoDSL.tokens");
	}
}
