/*
 * generated by Xtext
 */
package org.inria.diverse.logo.dsl.ui.contentassist

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class LogoDSLProposalProvider extends AbstractLogoDSLProposalProvider {
}
