/*
 * generated by Xtext
 */
package org.inria.diverse.logo.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LogoDSLUiModule extends AbstractLogoDSLUiModule {
	public LogoDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
