/**
 *
 * $Id$
 */
package kmLogo.VM.validation;

import kmLogo.VM.Point;

/**
 * A sample validator interface for {@link kmLogo.VM.Segment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SegmentValidator {
	boolean validate();

	boolean validateOrigin(Point value);
	boolean validateDestination(Point value);
}
