/**
 *
 * $Id$
 */
package kmLogo.VM.validation;

import kmLogo.VM.Point;
import kmLogo.VM.Segment;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link kmLogo.VM.Turtle}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TurtleValidator {
	boolean validate();

	boolean validatePosition(Point value);
	boolean validateDrawings(EList<Segment> value);
	boolean validateHeading(int value);
	boolean validatePenUp(Boolean value);
	boolean validatePoints(EList<Point> value);
}
