/*
 * generated by Xtext
 */
package org.inria.diverse.logo.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractLogoDSLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.inria.diverse.logo.dsl.logoDSL.LogoDSLPackage.eINSTANCE);
		return result;
	}
}
