/*
 * generated by Xtext
 */
package org.inria.diverse.logo.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LogoDSLRuntimeModule extends AbstractLogoDSLRuntimeModule {

}
