/*
 * generated by Xtext
 */
package org.inria.diverse.logo.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class LogoDSLUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.inria.diverse.logo.dsl.ui.internal.LogoDSLActivator.getInstance().getInjector("org.inria.diverse.logo.dsl.LogoDSL");
	}
	
}
